
// This file has been generated by the GUI designer. Do not modify.
namespace Examen
{
	public partial class SecondWindow
	{
		private global::Gtk.UIManager UIManager;

		private global::Gtk.Table table47;

		private global::Gtk.Table table1;

		private global::Gtk.Label t35;

		private global::Gtk.Label t36;

		private global::Gtk.Label t45;

		private global::Gtk.Label t46;

		private global::Gtk.Table table3;

		private global::Gtk.Label t13;

		private global::Gtk.Label t14;

		private global::Gtk.Label t23;

		private global::Gtk.Label t24;

		private global::Gtk.Table table4;

		private global::Gtk.Label t33;

		private global::Gtk.Label t34;

		private global::Gtk.Label t43;

		private global::Gtk.Label t44;

		private global::Gtk.Table table50;

		private global::Gtk.Label t53;

		private global::Gtk.Label t54;

		private global::Gtk.Label t63;

		private global::Gtk.Label t64;

		private global::Gtk.Table table52;

		private global::Gtk.Label t51;

		private global::Gtk.Label t52;

		private global::Gtk.Label t61;

		private global::Gtk.Label t62;

		private global::Gtk.Table table54;

		private global::Gtk.Label t31;

		private global::Gtk.Label t32;

		private global::Gtk.Label t41;

		private global::Gtk.Label t42;

		private global::Gtk.Table table56;

		private global::Gtk.Label t11;

		private global::Gtk.Label t12;

		private global::Gtk.Label t21;

		private global::Gtk.Label t22;

		private global::Gtk.Table table61;

		private global::Gtk.Label t15;

		private global::Gtk.Label t16;

		private global::Gtk.Label t25;

		private global::Gtk.Label t26;

		private global::Gtk.Table table65;

		private global::Gtk.Label t55;

		private global::Gtk.Label t56;

		private global::Gtk.Label t65;

		private global::Gtk.Label t66;

		protected virtual void Build()
		{
			global::Stetic.Gui.Initialize(this);
			// Widget Examen.SecondWindow
			this.UIManager = new global::Gtk.UIManager();
			global::Gtk.ActionGroup w1 = new global::Gtk.ActionGroup("Default");
			this.UIManager.InsertActionGroup(w1, 0);
			this.AddAccelGroup(this.UIManager.AccelGroup);
			this.Name = "Examen.SecondWindow";
			this.Title = global::Mono.Unix.Catalog.GetString("SecondWindow");
			this.WindowPosition = ((global::Gtk.WindowPosition)(4));
			// Container child Examen.SecondWindow.Gtk.Container+ContainerChild
			this.table47 = new global::Gtk.Table(((uint)(3)), ((uint)(3)), false);
			this.table47.Name = "table47";
			this.table47.RowSpacing = ((uint)(6));
			this.table47.ColumnSpacing = ((uint)(6));
			// Container child table47.Gtk.Table+TableChild
			this.table1 = new global::Gtk.Table(((uint)(2)), ((uint)(2)), false);
			this.table1.Name = "table1";
			this.table1.RowSpacing = ((uint)(6));
			this.table1.ColumnSpacing = ((uint)(6));
			// Container child table1.Gtk.Table+TableChild
			this.t35 = new global::Gtk.Label();
			this.t35.Name = "t35";
			this.table1.Add(this.t35);
			// Container child table1.Gtk.Table+TableChild
			this.t36 = new global::Gtk.Label();
			this.t36.Name = "t36";
			this.table1.Add(this.t36);
			global::Gtk.Table.TableChild w3 = ((global::Gtk.Table.TableChild)(this.table1[this.t36]));
			w3.LeftAttach = ((uint)(1));
			w3.RightAttach = ((uint)(2));
			// Container child table1.Gtk.Table+TableChild
			this.t45 = new global::Gtk.Label();
			this.t45.Name = "t45";
			this.table1.Add(this.t45);
			global::Gtk.Table.TableChild w4 = ((global::Gtk.Table.TableChild)(this.table1[this.t45]));
			w4.TopAttach = ((uint)(1));
			w4.BottomAttach = ((uint)(2));
			// Container child table1.Gtk.Table+TableChild
			this.t46 = new global::Gtk.Label();
			this.t46.Name = "t46";
			this.table1.Add(this.t46);
			global::Gtk.Table.TableChild w5 = ((global::Gtk.Table.TableChild)(this.table1[this.t46]));
			w5.TopAttach = ((uint)(1));
			w5.BottomAttach = ((uint)(2));
			w5.LeftAttach = ((uint)(1));
			w5.RightAttach = ((uint)(2));
			w5.XOptions = ((global::Gtk.AttachOptions)(4));
			w5.YOptions = ((global::Gtk.AttachOptions)(4));
			this.table47.Add(this.table1);
			global::Gtk.Table.TableChild w6 = ((global::Gtk.Table.TableChild)(this.table47[this.table1]));
			w6.TopAttach = ((uint)(1));
			w6.BottomAttach = ((uint)(2));
			w6.LeftAttach = ((uint)(2));
			w6.RightAttach = ((uint)(3));
			w6.XOptions = ((global::Gtk.AttachOptions)(4));
			w6.YOptions = ((global::Gtk.AttachOptions)(4));
			// Container child table47.Gtk.Table+TableChild
			this.table3 = new global::Gtk.Table(((uint)(2)), ((uint)(2)), false);
			this.table3.Name = "table3";
			this.table3.RowSpacing = ((uint)(6));
			this.table3.ColumnSpacing = ((uint)(6));
			// Container child table3.Gtk.Table+TableChild
			this.t13 = new global::Gtk.Label();
			this.t13.Name = "t13";
			this.table3.Add(this.t13);
			// Container child table3.Gtk.Table+TableChild
			this.t14 = new global::Gtk.Label();
			this.t14.Name = "t14";
			this.table3.Add(this.t14);
			global::Gtk.Table.TableChild w8 = ((global::Gtk.Table.TableChild)(this.table3[this.t14]));
			w8.LeftAttach = ((uint)(1));
			w8.RightAttach = ((uint)(2));
			w8.XOptions = ((global::Gtk.AttachOptions)(4));
			w8.YOptions = ((global::Gtk.AttachOptions)(4));
			// Container child table3.Gtk.Table+TableChild
			this.t23 = new global::Gtk.Label();
			this.t23.Name = "t23";
			this.table3.Add(this.t23);
			global::Gtk.Table.TableChild w9 = ((global::Gtk.Table.TableChild)(this.table3[this.t23]));
			w9.TopAttach = ((uint)(1));
			w9.BottomAttach = ((uint)(2));
			w9.XOptions = ((global::Gtk.AttachOptions)(4));
			w9.YOptions = ((global::Gtk.AttachOptions)(4));
			// Container child table3.Gtk.Table+TableChild
			this.t24 = new global::Gtk.Label();
			this.t24.Name = "t24";
			this.table3.Add(this.t24);
			global::Gtk.Table.TableChild w10 = ((global::Gtk.Table.TableChild)(this.table3[this.t24]));
			w10.TopAttach = ((uint)(1));
			w10.BottomAttach = ((uint)(2));
			w10.LeftAttach = ((uint)(1));
			w10.RightAttach = ((uint)(2));
			this.table47.Add(this.table3);
			global::Gtk.Table.TableChild w11 = ((global::Gtk.Table.TableChild)(this.table47[this.table3]));
			w11.LeftAttach = ((uint)(1));
			w11.RightAttach = ((uint)(2));
			w11.XOptions = ((global::Gtk.AttachOptions)(4));
			w11.YOptions = ((global::Gtk.AttachOptions)(4));
			// Container child table47.Gtk.Table+TableChild
			this.table4 = new global::Gtk.Table(((uint)(2)), ((uint)(2)), false);
			this.table4.Name = "table4";
			this.table4.RowSpacing = ((uint)(6));
			this.table4.ColumnSpacing = ((uint)(6));
			// Container child table4.Gtk.Table+TableChild
			this.t33 = new global::Gtk.Label();
			this.t33.Name = "t33";
			this.t33.LabelProp = global::Mono.Unix.Catalog.GetString("pacman");
			this.table4.Add(this.t33);
			// Container child table4.Gtk.Table+TableChild
			this.t34 = new global::Gtk.Label();
			this.t34.Name = "t34";
			this.table4.Add(this.t34);
			global::Gtk.Table.TableChild w13 = ((global::Gtk.Table.TableChild)(this.table4[this.t34]));
			w13.LeftAttach = ((uint)(1));
			w13.RightAttach = ((uint)(2));
			w13.XOptions = ((global::Gtk.AttachOptions)(4));
			w13.YOptions = ((global::Gtk.AttachOptions)(4));
			// Container child table4.Gtk.Table+TableChild
			this.t43 = new global::Gtk.Label();
			this.t43.Name = "t43";
			this.table4.Add(this.t43);
			global::Gtk.Table.TableChild w14 = ((global::Gtk.Table.TableChild)(this.table4[this.t43]));
			w14.TopAttach = ((uint)(1));
			w14.BottomAttach = ((uint)(2));
			w14.XOptions = ((global::Gtk.AttachOptions)(4));
			w14.YOptions = ((global::Gtk.AttachOptions)(4));
			// Container child table4.Gtk.Table+TableChild
			this.t44 = new global::Gtk.Label();
			this.t44.Name = "t44";
			this.table4.Add(this.t44);
			global::Gtk.Table.TableChild w15 = ((global::Gtk.Table.TableChild)(this.table4[this.t44]));
			w15.TopAttach = ((uint)(1));
			w15.BottomAttach = ((uint)(2));
			w15.LeftAttach = ((uint)(1));
			w15.RightAttach = ((uint)(2));
			this.table47.Add(this.table4);
			global::Gtk.Table.TableChild w16 = ((global::Gtk.Table.TableChild)(this.table47[this.table4]));
			w16.TopAttach = ((uint)(1));
			w16.BottomAttach = ((uint)(2));
			w16.LeftAttach = ((uint)(1));
			w16.RightAttach = ((uint)(2));
			w16.XOptions = ((global::Gtk.AttachOptions)(4));
			w16.YOptions = ((global::Gtk.AttachOptions)(4));
			// Container child table47.Gtk.Table+TableChild
			this.table50 = new global::Gtk.Table(((uint)(2)), ((uint)(2)), false);
			this.table50.Name = "table50";
			this.table50.RowSpacing = ((uint)(6));
			this.table50.ColumnSpacing = ((uint)(6));
			// Container child table50.Gtk.Table+TableChild
			this.t53 = new global::Gtk.Label();
			this.t53.Name = "t53";
			this.table50.Add(this.t53);
			// Container child table50.Gtk.Table+TableChild
			this.t54 = new global::Gtk.Label();
			this.t54.Name = "t54";
			this.table50.Add(this.t54);
			global::Gtk.Table.TableChild w18 = ((global::Gtk.Table.TableChild)(this.table50[this.t54]));
			w18.LeftAttach = ((uint)(1));
			w18.RightAttach = ((uint)(2));
			w18.XOptions = ((global::Gtk.AttachOptions)(4));
			w18.YOptions = ((global::Gtk.AttachOptions)(4));
			// Container child table50.Gtk.Table+TableChild
			this.t63 = new global::Gtk.Label();
			this.t63.Name = "t63";
			this.table50.Add(this.t63);
			global::Gtk.Table.TableChild w19 = ((global::Gtk.Table.TableChild)(this.table50[this.t63]));
			w19.TopAttach = ((uint)(1));
			w19.BottomAttach = ((uint)(2));
			w19.XOptions = ((global::Gtk.AttachOptions)(4));
			w19.YOptions = ((global::Gtk.AttachOptions)(4));
			// Container child table50.Gtk.Table+TableChild
			this.t64 = new global::Gtk.Label();
			this.t64.Name = "t64";
			this.table50.Add(this.t64);
			global::Gtk.Table.TableChild w20 = ((global::Gtk.Table.TableChild)(this.table50[this.t64]));
			w20.TopAttach = ((uint)(1));
			w20.BottomAttach = ((uint)(2));
			w20.LeftAttach = ((uint)(1));
			w20.RightAttach = ((uint)(2));
			this.table47.Add(this.table50);
			global::Gtk.Table.TableChild w21 = ((global::Gtk.Table.TableChild)(this.table47[this.table50]));
			w21.TopAttach = ((uint)(2));
			w21.BottomAttach = ((uint)(3));
			w21.LeftAttach = ((uint)(1));
			w21.RightAttach = ((uint)(2));
			// Container child table47.Gtk.Table+TableChild
			this.table52 = new global::Gtk.Table(((uint)(2)), ((uint)(2)), false);
			this.table52.Name = "table52";
			this.table52.RowSpacing = ((uint)(6));
			this.table52.ColumnSpacing = ((uint)(6));
			// Container child table52.Gtk.Table+TableChild
			this.t51 = new global::Gtk.Label();
			this.t51.Name = "t51";
			this.table52.Add(this.t51);
			global::Gtk.Table.TableChild w22 = ((global::Gtk.Table.TableChild)(this.table52[this.t51]));
			w22.XOptions = ((global::Gtk.AttachOptions)(4));
			w22.YOptions = ((global::Gtk.AttachOptions)(4));
			// Container child table52.Gtk.Table+TableChild
			this.t52 = new global::Gtk.Label();
			this.t52.Name = "t52";
			this.table52.Add(this.t52);
			global::Gtk.Table.TableChild w23 = ((global::Gtk.Table.TableChild)(this.table52[this.t52]));
			w23.LeftAttach = ((uint)(1));
			w23.RightAttach = ((uint)(2));
			// Container child table52.Gtk.Table+TableChild
			this.t61 = new global::Gtk.Label();
			this.t61.Name = "t61";
			this.table52.Add(this.t61);
			global::Gtk.Table.TableChild w24 = ((global::Gtk.Table.TableChild)(this.table52[this.t61]));
			w24.TopAttach = ((uint)(1));
			w24.BottomAttach = ((uint)(2));
			// Container child table52.Gtk.Table+TableChild
			this.t62 = new global::Gtk.Label();
			this.t62.Name = "t62";
			this.table52.Add(this.t62);
			global::Gtk.Table.TableChild w25 = ((global::Gtk.Table.TableChild)(this.table52[this.t62]));
			w25.TopAttach = ((uint)(1));
			w25.BottomAttach = ((uint)(2));
			w25.LeftAttach = ((uint)(1));
			w25.RightAttach = ((uint)(2));
			w25.XOptions = ((global::Gtk.AttachOptions)(4));
			w25.YOptions = ((global::Gtk.AttachOptions)(4));
			this.table47.Add(this.table52);
			global::Gtk.Table.TableChild w26 = ((global::Gtk.Table.TableChild)(this.table47[this.table52]));
			w26.TopAttach = ((uint)(2));
			w26.BottomAttach = ((uint)(3));
			// Container child table47.Gtk.Table+TableChild
			this.table54 = new global::Gtk.Table(((uint)(2)), ((uint)(2)), false);
			this.table54.Name = "table54";
			this.table54.RowSpacing = ((uint)(6));
			this.table54.ColumnSpacing = ((uint)(6));
			// Container child table54.Gtk.Table+TableChild
			this.t31 = new global::Gtk.Label();
			this.t31.Name = "t31";
			this.table54.Add(this.t31);
			// Container child table54.Gtk.Table+TableChild
			this.t32 = new global::Gtk.Label();
			this.t32.Name = "t32";
			this.table54.Add(this.t32);
			global::Gtk.Table.TableChild w28 = ((global::Gtk.Table.TableChild)(this.table54[this.t32]));
			w28.LeftAttach = ((uint)(1));
			w28.RightAttach = ((uint)(2));
			w28.XOptions = ((global::Gtk.AttachOptions)(4));
			w28.YOptions = ((global::Gtk.AttachOptions)(4));
			// Container child table54.Gtk.Table+TableChild
			this.t41 = new global::Gtk.Label();
			this.t41.Name = "t41";
			this.table54.Add(this.t41);
			global::Gtk.Table.TableChild w29 = ((global::Gtk.Table.TableChild)(this.table54[this.t41]));
			w29.TopAttach = ((uint)(1));
			w29.BottomAttach = ((uint)(2));
			w29.XOptions = ((global::Gtk.AttachOptions)(4));
			w29.YOptions = ((global::Gtk.AttachOptions)(4));
			// Container child table54.Gtk.Table+TableChild
			this.t42 = new global::Gtk.Label();
			this.t42.Name = "t42";
			this.table54.Add(this.t42);
			global::Gtk.Table.TableChild w30 = ((global::Gtk.Table.TableChild)(this.table54[this.t42]));
			w30.TopAttach = ((uint)(1));
			w30.BottomAttach = ((uint)(2));
			w30.LeftAttach = ((uint)(1));
			w30.RightAttach = ((uint)(2));
			this.table47.Add(this.table54);
			global::Gtk.Table.TableChild w31 = ((global::Gtk.Table.TableChild)(this.table47[this.table54]));
			w31.TopAttach = ((uint)(1));
			w31.BottomAttach = ((uint)(2));
			// Container child table47.Gtk.Table+TableChild
			this.table56 = new global::Gtk.Table(((uint)(2)), ((uint)(2)), false);
			this.table56.Name = "table56";
			this.table56.RowSpacing = ((uint)(6));
			this.table56.ColumnSpacing = ((uint)(6));
			// Container child table56.Gtk.Table+TableChild
			this.t11 = new global::Gtk.Label();
			this.t11.Name = "t11";
			this.t11.LabelProp = global::Mono.Unix.Catalog.GetString(" ");
			this.table56.Add(this.t11);
			global::Gtk.Table.TableChild w32 = ((global::Gtk.Table.TableChild)(this.table56[this.t11]));
			w32.XOptions = ((global::Gtk.AttachOptions)(4));
			w32.YOptions = ((global::Gtk.AttachOptions)(4));
			// Container child table56.Gtk.Table+TableChild
			this.t12 = new global::Gtk.Label();
			this.t12.Name = "t12";
			this.table56.Add(this.t12);
			global::Gtk.Table.TableChild w33 = ((global::Gtk.Table.TableChild)(this.table56[this.t12]));
			w33.LeftAttach = ((uint)(1));
			w33.RightAttach = ((uint)(2));
			// Container child table56.Gtk.Table+TableChild
			this.t21 = new global::Gtk.Label();
			this.t21.Name = "t21";
			this.table56.Add(this.t21);
			global::Gtk.Table.TableChild w34 = ((global::Gtk.Table.TableChild)(this.table56[this.t21]));
			w34.TopAttach = ((uint)(1));
			w34.BottomAttach = ((uint)(2));
			// Container child table56.Gtk.Table+TableChild
			this.t22 = new global::Gtk.Label();
			this.t22.Name = "t22";
			this.table56.Add(this.t22);
			global::Gtk.Table.TableChild w35 = ((global::Gtk.Table.TableChild)(this.table56[this.t22]));
			w35.TopAttach = ((uint)(1));
			w35.BottomAttach = ((uint)(2));
			w35.LeftAttach = ((uint)(1));
			w35.RightAttach = ((uint)(2));
			this.table47.Add(this.table56);
			// Container child table47.Gtk.Table+TableChild
			this.table61 = new global::Gtk.Table(((uint)(2)), ((uint)(2)), false);
			this.table61.Name = "table61";
			this.table61.RowSpacing = ((uint)(6));
			this.table61.ColumnSpacing = ((uint)(6));
			// Container child table61.Gtk.Table+TableChild
			this.t15 = new global::Gtk.Label();
			this.t15.Name = "t15";
			this.table61.Add(this.t15);
			// Container child table61.Gtk.Table+TableChild
			this.t16 = new global::Gtk.Label();
			this.t16.Name = "t16";
			this.table61.Add(this.t16);
			global::Gtk.Table.TableChild w38 = ((global::Gtk.Table.TableChild)(this.table61[this.t16]));
			w38.LeftAttach = ((uint)(1));
			w38.RightAttach = ((uint)(2));
			w38.YOptions = ((global::Gtk.AttachOptions)(4));
			// Container child table61.Gtk.Table+TableChild
			this.t25 = new global::Gtk.Label();
			this.t25.Name = "t25";
			this.table61.Add(this.t25);
			global::Gtk.Table.TableChild w39 = ((global::Gtk.Table.TableChild)(this.table61[this.t25]));
			w39.TopAttach = ((uint)(1));
			w39.BottomAttach = ((uint)(2));
			w39.XOptions = ((global::Gtk.AttachOptions)(4));
			w39.YOptions = ((global::Gtk.AttachOptions)(4));
			// Container child table61.Gtk.Table+TableChild
			this.t26 = new global::Gtk.Label();
			this.t26.Name = "t26";
			this.table61.Add(this.t26);
			global::Gtk.Table.TableChild w40 = ((global::Gtk.Table.TableChild)(this.table61[this.t26]));
			w40.TopAttach = ((uint)(1));
			w40.BottomAttach = ((uint)(2));
			w40.LeftAttach = ((uint)(1));
			w40.RightAttach = ((uint)(2));
			w40.XOptions = ((global::Gtk.AttachOptions)(4));
			this.table47.Add(this.table61);
			global::Gtk.Table.TableChild w41 = ((global::Gtk.Table.TableChild)(this.table47[this.table61]));
			w41.LeftAttach = ((uint)(2));
			w41.RightAttach = ((uint)(3));
			// Container child table47.Gtk.Table+TableChild
			this.table65 = new global::Gtk.Table(((uint)(2)), ((uint)(2)), false);
			this.table65.Name = "table65";
			this.table65.RowSpacing = ((uint)(6));
			this.table65.ColumnSpacing = ((uint)(6));
			// Container child table65.Gtk.Table+TableChild
			this.t55 = new global::Gtk.Label();
			this.t55.Name = "t55";
			this.table65.Add(this.t55);
			// Container child table65.Gtk.Table+TableChild
			this.t56 = new global::Gtk.Label();
			this.t56.Name = "t56";
			this.table65.Add(this.t56);
			global::Gtk.Table.TableChild w43 = ((global::Gtk.Table.TableChild)(this.table65[this.t56]));
			w43.LeftAttach = ((uint)(1));
			w43.RightAttach = ((uint)(2));
			w43.XOptions = ((global::Gtk.AttachOptions)(4));
			w43.YOptions = ((global::Gtk.AttachOptions)(4));
			// Container child table65.Gtk.Table+TableChild
			this.t65 = new global::Gtk.Label();
			this.t65.Name = "t65";
			this.table65.Add(this.t65);
			global::Gtk.Table.TableChild w44 = ((global::Gtk.Table.TableChild)(this.table65[this.t65]));
			w44.TopAttach = ((uint)(1));
			w44.BottomAttach = ((uint)(2));
			w44.YOptions = ((global::Gtk.AttachOptions)(4));
			// Container child table65.Gtk.Table+TableChild
			this.t66 = new global::Gtk.Label();
			this.t66.Name = "t66";
			this.table65.Add(this.t66);
			global::Gtk.Table.TableChild w45 = ((global::Gtk.Table.TableChild)(this.table65[this.t66]));
			w45.TopAttach = ((uint)(1));
			w45.BottomAttach = ((uint)(2));
			w45.LeftAttach = ((uint)(1));
			w45.RightAttach = ((uint)(2));
			this.table47.Add(this.table65);
			global::Gtk.Table.TableChild w46 = ((global::Gtk.Table.TableChild)(this.table47[this.table65]));
			w46.TopAttach = ((uint)(2));
			w46.BottomAttach = ((uint)(3));
			w46.LeftAttach = ((uint)(2));
			w46.RightAttach = ((uint)(3));
			this.Add(this.table47);
			if ((this.Child != null))
			{
				this.Child.ShowAll();
			}
			this.DefaultWidth = 400;
			this.DefaultHeight = 300;
			this.Show();
		}
	}
}
