
// This file has been generated by the GUI designer. Do not modify.
namespace Examen
{
	public partial class Window2
	{
		protected virtual void Build()
		{
			global::Stetic.Gui.Initialize(this);
			// Widget Examen.Window2
			this.Name = "Examen.Window2";
			this.Title = global::Mono.Unix.Catalog.GetString("Window2");
			this.WindowPosition = ((global::Gtk.WindowPosition)(4));
			if ((this.Child != null))
			{
				this.Child.ShowAll();
			}
			this.DefaultWidth = 400;
			this.DefaultHeight = 300;
			this.Show();
		}
	}
}
