
// This file has been generated by the GUI designer. Do not modify.
namespace Examen
{
	public partial class ThirdWindow
	{
		protected virtual void Build()
		{
			global::Stetic.Gui.Initialize(this);
			// Widget Examen.ThirdWindow
			this.Name = "Examen.ThirdWindow";
			this.Title = global::Mono.Unix.Catalog.GetString("ThirdWindow");
			this.WindowPosition = ((global::Gtk.WindowPosition)(4));
			if ((this.Child != null))
			{
				this.Child.ShowAll();
			}
			this.DefaultWidth = 400;
			this.DefaultHeight = 300;
			this.Show();
		}
	}
}
